UKHomeOffice/gro

- apps/common/views/layout.html
- apps/common/views/partials/gatag.html
https://jira.digital.homeoffice.gov.uk/browse/GFM-11
* Added GA Tag partial which adds the script to the page if locals.gaTagId is defined
* Added partial to layout.html
> GFM-11 - Implemented GA Tagging

- test/unit/apps/common/controllers/start.js
- test/unit/apps/gro/controllers/confirm.js
- test/unit/apps/gro/controllers/post.js
- test/unit/apps/gro/controllers/when.js
Unit tests for the controllers that are used in gro have been added
> Dev task/controllers unit tests

- apps/gro/controllers/confirm.js
- test/unit/apps/gro/controllers/confirm.js
Changed the way the sessionModel attributes were added to the object 'd' using underscore to make it simpler and easier to understand.
Removed the logic around the service as it was unnecessary. It would always go into the if statement as service is always set as a variable. 
Removing this has also put gro at 100% coverage!
> Tidying up confirm controller

- README.md
- acceptance_tests/features/support/config_ci.yml
- acceptance_tests/features/support/config_docker.yml
- acceptance_tests/features/support/config_test.yml
- apps/gro/index.js
- update the tests
- update the readme
- replace the baseurl passed to wizard in apps/gro/index.js
> Replace baseurl 'certificate-enquiries/' with '/'

- acceptance_tests/features/support/content.yml
- apps/gro/fields/about.js
- apps/gro/fields/additional.js
- apps/gro/fields/details.js
- apps/gro/fields/email.js
- apps/gro/fields/how.js
- apps/gro/fields/people.js
- apps/gro/fields/person.js
- apps/gro/fields/type.js
- apps/gro/fields/when.js
- apps/gro/fields/which.js
- apps/gro/translations/src/en/fields.json
- apps/gro/translations/src/en/pages.json
- apps/gro/views/about.html
- apps/gro/views/additional.html
- apps/gro/views/details.html
- apps/gro/views/email.html
- apps/gro/views/how.html
- apps/gro/views/name.html
- apps/gro/views/people.html
- apps/gro/views/person.html
- apps/gro/views/post.html
- apps/gro/views/type.html
- apps/gro/views/when.html
- apps/gro/views/which.html
* Added section headers to each page to replace label title.
* Added labels to first input
* Added custom sub-title to post step
> GFM-86 - Use section headers as titles

- acceptance_tests/features/back_links.feature
- acceptance_tests/features/change_answers.feature
- acceptance_tests/features/happy.feature
- acceptance_tests/features/step_definitions/shared_steps.rb
- acceptance_tests/features/support/content.yml
- acceptance_tests/features/validations.feature
- apps/gro/fields/which.js
- apps/gro/steps.js
- apps/gro/translations/src/en/fields.json
- apps/gro/translations/src/en/validation.json
- apps/gro/views/which.html
* removed order-number field along with associated translations
> GFM-78 - content changes to /which step

- apps/gro/translations/src/en/fields.json
* Removed hint from email field
> GFM-79 - content changes on the /email step

- apps/gro/translations/src/en/fields.json
* changed label for Damaged or badly printed certificate to "Poor quality certificate"
* changed label for Other to "Other issues and feedback"
> GFM-73 - content changes to about step

- acceptance_tests/features/postcode.feature
- acceptance_tests/features/step_definitions/shared_steps.rb
- acceptance_tests/features/support/content.yml
- apps/common/views/partials/contact-details.html
- apps/gro/controllers/address.js
- apps/gro/fields/address-outside.js
- apps/gro/steps.js
- apps/gro/translations/src/en/fields.json
- apps/gro/translations/src/en/pages.json
- apps/gro/views/address-inside.html
- apps/gro/views/address-outside.html
- apps/gro/views/no-postcode.html
- apps/gro/views/postcode.html
- assets/scss/app.scss
- test/unit/apps/gro/controllers/address.js
* Modified address controller
* Change views - address-inside, address-outside, no-postcode, postcode
* Modified summary partial - contact-details
* Modified Steps to use single field
* Modified address-outside fields to use flag ignore-defaults to ignore default formatters
> GFM-69 - Change from 5 line addresses to 1 textarea

- apps/common/models/email.js
- apps/gro/fields/index.js
- package.json
- Replaced underscore with lodash
- Remove underscore from package.json
> GFM-95 Remove Underscore

- apps/gro/steps.js
GFM-100 Changed the fork condition functions in steps.js from 
```
condition: function something(req) {}
```
to 
```
condition(req) {}
```
> GFM-100 Fork Condition Functions in step.js

- apps/gro/steps.js
Removed template from the steps where the route name and template name are the same
> GFM-101 Removed template from steps

- Dockerfile
- app.js
- docker-compose.yml
- run.sh
- remove NODE_ENV='development' setting from Dockerfile
- remove the condition for NODE_ENV='development' from run.sh
- always use `npm start` to run the app in a container
> Resolve GFM-118: Fix Docker build

- .travis.yml
- app.js
- apps/common/controllers/start.js
- apps/gro/controllers/address-lookup.js
- apps/gro/controllers/postcode.js
- assets/js/index.js
- assets/scss/app.scss
- ci.js
- config.js
- lib/logger.js
- package.json
- services/email/index.js
- test/unit/apps/common/models/email.js
- test/unit/apps/gro/controllers/postcode.js
* removed from deps
* fixed lint
> bugfix GFM-119 - use hof version of eslint and eslint-config-homeoffice

- app.js
- remove the condition that stops express serving static in ENV VAR = docker
> Always serve static from Node/Express

- acceptance_tests/features/support/content.yml
- apps/gro/translations/src/en/fields.json
* Use new conditional labels to change label for person depending on about-radio
> GFM-75 - updated /person to use conditional labels

- apps/gro/fields/details.js
* replaced field mixin with textarea
* removed default formatters
* reapply trim and hyphens formatters
> GFM-113 - replaced input-text with textarea for details-text field

- apps/gro/index.js
* deep cloned fields and steps in apps/gro/index.js
* updated to use const rather than var
> GFM-122 - deepClone fields/steps

- Dockerfile
- Jenkinsfile
- app.js
- apps/common/services/email.js
- apps/common/translations/src/en/errors.json
- apps/gro/controllers/confirm.js
- apps/gro/index.js
- config.js
- docker-compose.yml
- kube/services/k8resources/gro/gro-rc.yaml
- run.sh
This PR also fixes a few other issues that I've encountered along the way.
> Migrate our docker-compose to v2 which has way less madness (we now just use the service names as the hosts)

- .travis.yml
* moved `npm start` to scripts
* run as one command split with `&&`'s
> bugfix - fix travis not stopping on error

- app.js
* moved app init code to i18n on ready callback
* moved require calls to top of file
> GFM-148 - wait for translations to be loaded before starting app

- acceptance_tests/features/support/content.yml
- acceptance_tests/features/validations.feature
- apps/gro/translations/src/en/fields.json
- apps/gro/translations/src/en/validation.json
* refined previous error message
* added existing error message for other enquiries
* added acceptance tests
> GFM-151 - refine error message

- apps/gro/controllers/confirm.js
- apps/gro/services/email.js
- config.js
- log email error
- provide correct paths to image resources
> Update email confiig and logging

- apps/gro/controllers/address-lookup.js
- test/unit/apps/gro/controllers/address-lookup.js
* use objects for options to stop implicit lookup
> fix for address lookup

- assets/scss/app.scss
Added white-space: pre-wrap to summary table cell styles.
> Bugfix GFM-166 - preserve carriage return

- apps/gro/controllers/confirm.js
* switched .toISOString to .toUTCString for date of submission
> GFM-165 - display human readable date

- acceptance_tests/features/alternate_content.feature
- acceptance_tests/features/step_definitions/shared_steps.rb
- acceptance_tests/features/support/content.yml
- apps/gro/confirm-step-config.js
- apps/gro/translations/src/en/pages.json
* changed table selector to lookup via data-value, not content
* fixed typo in current acceptance tests
* added \n chars to address
> bugfix - fix acceptance tests

- apps/gro/controllers/address-lookup.js
* added post hook to controller to get values from session and reset options
> bugfix - Address lookup options cleared on POST

- apps/gro/services/email.js
- config.js
* added replyTo to email config - reads from REPLY_TO env var
* use replyTo when sending mail
> task - GFM-176 - add replyTo field

- docker-compose.yml
> Revert "Task/gfm 187/waf tweaks"

- acceptance_tests/features/support/content.yml
- apps/gro/translations/src/en/validation.json
updated date validatoion message - on an invalid date (29/02/2016) show generic message - Enter a valid date
> bugfix - GFDM-179

- README.md
We use browserstack for mobile and desktop testing.
> Add props to browserstack

- apps/gro/views/email/data-row.html
- apps/gro/views/email/formatted.html
- apps/gro/views/email/layout.html
- apps/gro/views/email/raw.html
- apps/gro/views/email/section-row.html
- apps/gro/views/email/text-header.html
- config.js
The templates were broken in the version that's used so we're bringing them into the app to fix them locally instead
> Fixup broken rendering in hof-emailer

- README.md
- hof.settings.json
Update service name from registrars -> register
This is the proper name
> GRO-103: Update app name from registrar to register

- .snyk
- package.json
- yarn.lock
HOFF-257 - Updated HOF to enable GA4
> HOFF-257 - Updated HOF to enable GA4

- .snyk
- package.json
- yarn.lock
What
Upgrade HOF version to v20.1.14
Why
To fix issue with radio buttons not working when js has been disabled
How
* Update package.json
* Update yarn.lock
> GRO-118: Update HOF

- assets/scss/app.scss
- package.json
- yarn.lock
Changed links colour to #1D70B8 and visited-colour to #4C2C92
> Changed the links and visited colour to GDS standard

- .snyk
- kube/app/ingress-external.yml
- kube/app/ingress-internal.yml
Updated ingress due to breaking change
> Updated ingress due to breaking change

- test/helpers/supertest_session/session-data/gro/pages/confirmation.js
What
add confirmation.js helper
How
In the helper pages add the confirmation.js the same that confirm.js
Why
The test is failing as doesn't find confirmation.
> Fixing acceptance test
