.travis.yml
https://jira.digital.homeoffice.gov.uk/browse/GFM-32
* Removed node version 0.12 and added 4, 4.2 and 5 to Travis config
* Split Travis script to separate tasks, added before_script step to run sass and start app
* Removed acceptance test step for now until migration complete
=> GFM-32 - Changed travis config to use recent versions of node

Dockerfile
This replaced the GRO Dockerfile with the generic hod homeoffice Dockerfile.  Uses ONBUILD to standardise our repos so there's not very much login in this itself.
=> set it so we use common dockerfile

package.json
* node-sass is broken from version 3.5.1 onwards
* fixed to latest working version - 3.5.0-beta.1
=> Fix version of node-sass to latest working version

.dockerignore, .eslintignore, .gitignore, .istanbul.yml, .jscsrc.json, package.json
- add istanbul (unit test code coverage tool) to scripts
- configure coverage (istanbul.yml)
- add `cover` to pre commit hooks.
- ignore coverage output
I've the set the coverage target at 80% and you can't commit unless the cover meets 80%!!!
Let's win at unit tests
`npm run cover`
=> Add test coverage to precommit hook

kube/services/environments/dev.yaml, kube/services/k8resources/gro/gro-rc.yaml
adds postcode auth secret to the deploy scripts.  This is already pre-seeded into s3
=> add postcode auth secret

.travis.yml
this is because only a certain amount of agents can run concurrently so by testing 3 versions of node we sometimes double the time it takes to build (12 mins rather than 6)
=> Removed node v4 from Travis config

apps/gro/steps.js
* removed backLinks from forked pages - these are generated automatically and this was only a workaround for hmpo-form-wizard backLinks middleware not being aware of forking
* removed prereqs from forked pages - as above, the check-progress middleware is now aware of forks so this is no longer needed
=> GFM-90 - remove backLinks and prereqs

apps/common/views/layout.html, apps/common/views/partials/maincontent-left.html
Fixed styling issue with backLinks by moving the backLink partial from the maincontent-left template to the layout template.
BEFORE:
AFTER:
=> Back links styling wrong

apps/common/fields/index.js, apps/gro/index.js
- Deleted the fields directory in the common directory. 
- Made changes to the index.js in the gro directory to reflect this changed. 
- Removed underscore from this file as it is now not being used.
=> GRO Form MigrationGFM-96 Remove `apps/common/fields`

Dockerfile
- copy https://github.com/UKHomeOffice/docker-nodejs contents to GRO Dockerfile
- add `RUN npm instal -g npm@3`
Due to a change in hmpo-frontend-toolkit@4.1.0, and when we use npm 2, which runs postinstall before npm install, then the build breaks. 
This pr introduces a change to the Dockerfile that installs npm 3, which runs postinstall before install
=> Override https://github.com/UKHomeOffice/docker-nodejs to install npm 3

apps/gro/index.js
* applied deepTranslate middleware before mixins and wizard
* removed translate function from middleware and wizard - they will use `req.translate` if a translation method is not provided directly
=> feature - use deepTranslate middleware

app.js, apps/common/translations/src/en/errors.json, apps/common/views/404.html, apps/common/views/error.html
- invoke i18n with a path to the translations before assigning translate
- use hof cookie middleware before alls routes
- use not found middleware before error handler
- don't pass debug to error handler; we want to see the translations
- add cookie and not found translations to the translations file
- add a 404 template
- make start link a slash.
=> Fix middleware implemetnation

Dockerfile, Jenkinsfile, docker-compose.yml, kube/services/k8resources/gro/gro-rc.yaml, package.json, run.sh
* Quote ports and error codes to make yaml parsers happy in the kube controller
* Fix /public serving issue
Ensure docker file creates a public dir and moves files into it
Refactor docker file to cache more build steps.
Remove the need for tests in our docker file (this should be done outside of here)
* Make docker-compose reflect kubernetes better
* Add /public mount points in kubernetes for the nginx proxy
* Ensure public can be shared in kubernetes.
Sadly kube doesn't have a volumes-from feature like in compose so you have to do something yucky like making an emptyDir then copying the files in from a shell script :(
* Our build shouldn't be one giant pipeline.
It should have other builds to do this else we literally never get a green build unless we deploy to prod (lulz).
* Fix jenkins …
=> Fix up multiple issues with the build:

acceptance_tests/features/postcode.feature, acceptance_tests/features/step_definitions/shared_steps.rb, acceptance_tests/features/support/content.yml, apps/gro/controllers/address.js, apps/gro/fields/address.js, apps/gro/translations/src/en/pages.json, apps/gro/views/address.html, apps/gro/views/postcode.html, test/unit/apps/gro/controllers/address.js
* added link to postcode page, uses action: manual
* amended address page to not show amend postcode link if not defined
* unset postcode on address step if manual link was clicked
* fix bug with address error not showing
* added to acceptance tests
=> GFM-116 - added manual-entry link to postcode page

apps/gro/fields/about.js, apps/gro/fields/additional.js, apps/gro/fields/details.js, apps/gro/fields/how.js, apps/gro/fields/type.js, apps/gro/fields/which.js, apps/gro/translations/src/en/fields.json
Due to an enhancement in hmpo-template-mixins, radio options are now looked up automatically if located at the correct path within translations
* removed all explicit label paths
* added missing labels to translations
=> GFM-172 - lookup radio options labels implicitly

apps/gro/confirm-step-config.js
we were previously displaying the values from radios which are lowercase and hyphenated.
* added modifier lookup function to all radio fields
=> bugfix - GFM-174 - display labels in confirm table

apps/gro/fields/how.js
This was removed in a previous PR but seems to be back due a conflicting merge
* removed toggle content and just passed string reprentation
=> bugfix - GFM-175 - remove post option toggle field

docker-compose.yml
WAF tweaks for docker-compose to allow double quotes and commas in address selection
=> Task/gfm 187/waf tweaks

acceptance_tests/features/alternate_content.feature, acceptance_tests/features/change_answers.feature, acceptance_tests/features/happy.feature, acceptance_tests/features/postcode.feature, acceptance_tests/features/support/content.yml, apps/gro/controllers/address.js, apps/gro/controllers/confirm.js, apps/gro/fields.js, apps/gro/index.js, apps/gro/translations/src/en/fields.json, test/unit/apps/gro/controllers/confirm.js
* added confirm controller
* if address-lookup set then don't show address-textarea
* if manual address set, unset address-lookup
* updated tests
=> bugfix GFM-195 - confirm page address change link broken

package.json
The path needs to have `src/` on the end or it detects js files in the parent directory too.
=> Fix path for common translations

package-lock.json, package.json
The package shipped a breaking change in 1.1.0, which causes an error at start-up time. Force this project to use 1.0.0 to work around.
=> Push version of deprecate back to 1.0.0

.drone.yml, Dockerfile, README.md, docker-compose.yml, package.json, server.js, yarn.lock
- for v2.5.0
- GRO-121: Node 18 upgrade
- GRO-111: GA4 migration with new CSP rules
- GRO-143: Update HOF framework to v20.2.10
=> Release branch v2.5.0 

.drone.yml
What?
I've added Trivy Scanner to Pipeline and removed deprecated Anchore Scanner for the GRO service, see ticket
[https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-610](url)
Why?
Trivy will let you scan images, file systems and repositories for any vulnerabilities and issues. It will detect CVEs of OS packages, applications susceptibilities, and exposures of IaC in Terraform files, Kubernetes and Docker.
Drawback of Anchore Scanner is it’s significantly slower, the process of using it is more cumbersome, the output is less friendly and most importantly, it scans fewer CVEs.
See [https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-610](url) for more information.
How?
Removed Anchore cve exception file and added trivy cve exception file in hof-services-config repo from GRO …
=> WIP -DO NOT MERGE - HOFF-610: Replace Anchore with Trivy

package.json, yarn.lock
[HOFF-636 ](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-636).- changing Queen's crown to King's crown logo
 
The Gov.uk crown logo changed.
yarn install hof@20.4.0
 
Tested locally
 
 
=> HOFF-636 Update GRO to HOF v20.4.0

package.json, yarn.lock
- Update gro to use version of hof which replaces request module with axios - [HOFF-657](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-657)
- The request module in hof is deprecated and has vulnerabilities so  has been replaced by axios.
- update hof version to use axios
- update yarn.lock
- tests passing locally
=> HOFF-657: Update GRO to version of hof using axios

apps/gro/views/accessibility.html, package.json
Updated accessibility statement.  
https://collaboration.homeoffice.gov.uk/jira/browse/GRO-215
- noted site is fully compliant with WCAG 2.2 AA. Deleted out of date lines (accessibility.html)
- minor formatting (package.json)
https://are-are-135-accessibilitystatement.internal.are-branch.homeoffice.gov.uk/accessibility.html
the accessibility statement should say that it is fully compliant with the WCAG 2.2 AA standard.  
here is an [example commit](https://github.com/UKHomeOfficeForms/hof/commit/810959f391187c7c4af6db262bcd143b50093a6e)
=> GRO-215: Update Accessibility Statement
